@ExcelDataManagementAPI_HostAddress = http://localhost:5201
@MacroAPI_HostAddress = http://localhost:5002

# Excel API Test
GET {{ExcelDataManagementAPI_HostAddress}}/weatherforecast/
Accept: application/json

### Excel API Basic Test
GET {{MacroAPI_HostAddress}}/api/excel/test
Accept: application/json

### ========= MACRO API TESTS =========

### Macro API Test
GET {{MacroAPI_HostAddress}}/api/macro/test
Accept: application/json

### Mevcut dosyalarý listele
GET {{MacroAPI_HostAddress}}/api/macro/available-files
Accept: application/json

### Dosya numarasý ara (örnek)
GET {{MacroAPI_HostAddress}}/api/macro/search-by-document/1010007261000100
Accept: application/json

### Dosya numarasý ara - belirli dosyada
GET {{MacroAPI_HostAddress}}/api/macro/search-by-document/1010007261000100?fileName=test_dosya.xlsx
Accept: application/json

### Dosya numarasý ara - belirli sheet'te
GET {{MacroAPI_HostAddress}}/api/macro/search-by-document/1010007261000100?sheetName=Sheet1
Accept: application/json

### Dosya numarasý istatistikleri
GET {{MacroAPI_HostAddress}}/api/macro/document-statistics/1010007261000100
Accept: application/json

### Dosya numarasý bazlý veri güncelleme
PUT {{MacroAPI_HostAddress}}/api/macro/update-document-data
Content-Type: application/json

{
  "documentNumber": "1010007261000100",
  "rowId": 1,
  "updateData": {
    "kolon1": "yeni deðer 1",
    "kolon2": "yeni deðer 2"
  },
  "updatedBy": "test_user"
}

### Dosya numarasý bazlý toplu güncelleme
PUT {{MacroAPI_HostAddress}}/api/macro/bulk-update-document
Content-Type: application/json

{
  "documentNumber": "1010007261000100",
  "updates": [
    {
      "rowId": 1,
      "updateData": {
        "kolon1": "toplu güncelleme 1"
      }
    },
    {
      "rowId": 2,
      "updateData": {
        "kolon2": "toplu güncelleme 2"
      }
    }
  ],
  "updatedBy": "bulk_update_user"
}

### ========= EXCEL API TESTS (Destek için) =========

### Excel dosyasý yükle
POST {{MacroAPI_HostAddress}}/api/excel/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./test.xlsx
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="uploadedBy"

test_user
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Yüklü dosyalarý listele
GET {{MacroAPI_HostAddress}}/api/excel/files
Accept: application/json

### Excel dosyasýný oku
POST {{MacroAPI_HostAddress}}/api/excel/read/test.xlsx
Accept: application/json

### Excel verisini getir
GET {{MacroAPI_HostAddress}}/api/excel/data/test.xlsx
Accept: application/json

### Excel verisini getir - belirli sayfa
GET {{MacroAPI_HostAddress}}/api/excel/data/test.xlsx?page=1&pageSize=10
Accept: application/json
````````


# Response
